name: Renode Automated multi memory configurations

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  renode_automated_multi_memory:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Select config
        run: |
          cp config/examples/nrf52840.config .config && make include/target.h

##### SMALL STACK tests

# SIGN=NONE TEST
      - name: Renode Tests SIGN=NONE WOLFBOOT_SMALL_STACK=1
        run: ./tools/renode/docker-test.sh "SIGN=NONE WOLFBOOT_SMALL_STACK=1"


# ECC256 TEST
      - name: Renode Tests ECC256
        run: ./tools/renode/docker-test.sh "SIGN=ECC256 WOLFBOOT_SMALL_STACK=1"


# ECC384 TEST
      - name: Renode Tests ECC384
        run: ./tools/renode/docker-test.sh "SIGN=ECC384 WOLFBOOT_SMALL_STACK=1"


# ED25519 TEST
      - name: Renode Tests ED25519
        run: ./tools/renode/docker-test.sh "SIGN=ED25519 WOLFBOOT_SMALL_STACK=1"


# ED448 TEST
      - name: Renode Tests ED448
        run: ./tools/renode/docker-test.sh "SIGN=ED448 WOLFBOOT_SMALL_STACK=1"


# RSA2048 TEST
      - name: Renode Tests RSA2048
        run: ./tools/renode/docker-test.sh "SIGN=RSA2048 WOLFBOOT_SMALL_STACK=1"


# RSA3072 TEST
      - name: Renode Tests RSA3072
        run: ./tools/renode/docker-test.sh "SIGN=RSA3072 WOLFBOOT_SMALL_STACK=1"


# RSA4096 TEST
      - name: Renode Tests RSA4096
        run: ./tools/renode/docker-test.sh "SIGN=RSA4096 WOLFBOOT_SMALL_STACK=1"


      - name: Upload Output Dir
        uses: actions/upload-artifact@v2
        with:
          name: Renode Test Results
          path: test_results/

##### NO_ASM tests

# ECC256 TEST
      - name: Renode Tests ECC256
        run: ./tools/renode/docker-test.sh "SIGN=ECC256 NO_ASM=1"


# ECC384 TEST
      - name: Renode Tests ECC384
        run: ./tools/renode/docker-test.sh "SIGN=ECC384 NO_ASM=1"


# ED25519 TEST
      - name: Renode Tests ED25519
        run: ./tools/renode/docker-test.sh "SIGN=ED25519 NO_ASM=1"


# ED448 TEST
      - name: Renode Tests ED448
        run: ./tools/renode/docker-test.sh "SIGN=ED448 NO_ASM=1"


# RSA2048 TEST
      - name: Renode Tests RSA2048
        run: ./tools/renode/docker-test.sh "SIGN=RSA2048 NO_ASM=1"


# RSA3072 TEST
      - name: Renode Tests RSA3072
        run: ./tools/renode/docker-test.sh "SIGN=RSA3072 NO_ASM=1"


# RSA4096 TEST
      - name: Renode Tests RSA4096
        run: ./tools/renode/docker-test.sh "SIGN=RSA4096 NO_ASM=1"


      - name: Upload Output Dir
        uses: actions/upload-artifact@v2
        with:
          name: Renode Test Results
          path: test_results/

##### SMALL STACK + NO_ASM tests

# ECC256 TEST
      - name: Renode Tests ECC256
        run: ./tools/renode/docker-test.sh "SIGN=ECC256 WOLFBOOT_SMALL_STACK=1 NO_ASM=1"


# ECC384 TEST
      - name: Renode Tests ECC384
        run: ./tools/renode/docker-test.sh "SIGN=ECC384 WOLFBOOT_SMALL_STACK=1 NO_ASM=1"


# RSA2048 TEST
      - name: Renode Tests RSA2048
        run: ./tools/renode/docker-test.sh "SIGN=RSA2048 WOLFBOOT_SMALL_STACK=1 NO_ASM=1"


# RSA3072 TEST
      - name: Renode Tests RSA3072
        run: ./tools/renode/docker-test.sh "SIGN=RSA3072 WOLFBOOT_SMALL_STACK=1 NO_ASM=1"


# RSA4096 TEST
      - name: Renode Tests RSA4096
        run: ./tools/renode/docker-test.sh "SIGN=RSA4096 WOLFBOOT_SMALL_STACK=1 NO_ASM=1"


      - name: Upload Output Dir
        uses: actions/upload-artifact@v2
        with:
          name: Renode Test Results
          path: test_results/

##### FAST MATH tests

# ECC256 TEST
      - name: Renode Tests ECC256
        run: ./tools/renode/docker-test.sh "SIGN=ECC256 SPMATH=0"


# ECC384 TEST
      - name: Renode Tests ECC384
        run: ./tools/renode/docker-test.sh "SIGN=ECC384 SPMATH=0"


# RSA2048 TEST
      - name: Renode Tests RSA2048
        run: ./tools/renode/docker-test.sh "SIGN=RSA2048 SPMATH=0"


# RSA3072 TEST
      - name: Renode Tests RSA3072
        run: ./tools/renode/docker-test.sh "SIGN=RSA3072 SPMATH=0"


# RSA4096 TEST
      - name: Renode Tests RSA4096
        run: ./tools/renode/docker-test.sh "SIGN=RSA4096 SPMATH=0"


      - name: Upload Output Dir
        uses: actions/upload-artifact@v2
        with:
          name: Renode Test Results
          path: test_results/

##### SMALL STACK + FAST MATH tests

# ECC256 TEST
      - name: Renode Tests ECC256
        run: ./tools/renode/docker-test.sh "SIGN=ECC256 WOLFBOOT_SMALL_STACK=1 SPMATH=0"


# ECC384 TEST
      - name: Renode Tests ECC384
        run: ./tools/renode/docker-test.sh "SIGN=ECC384 WOLFBOOT_SMALL_STACK=1 SPMATH=0"


# RSA2048 TEST
      - name: Renode Tests RSA2048
        run: ./tools/renode/docker-test.sh "SIGN=RSA2048 WOLFBOOT_SMALL_STACK=1 SPMATH=0"


# RSA3072 TEST
      - name: Renode Tests RSA3072
        run: ./tools/renode/docker-test.sh "SIGN=RSA3072 WOLFBOOT_SMALL_STACK=1 SPMATH=0"


# RSA4096 TEST
      - name: Renode Tests RSA4096
        run: ./tools/renode/docker-test.sh "SIGN=RSA4096 WOLFBOOT_SMALL_STACK=1 SPMATH=0"


      - name: Upload Output Dir
        uses: actions/upload-artifact@v2
        with:
          name: Renode Test Results
          path: test_results/

